# Generated by Django 6.0 on 2026-04-07 16:40

import events.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_calendarfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarfile',
            name='file',
            field=models.FileField(storage=events.storages.PublicRawCloudinaryStorage(), upload_to='calendars/'),
        ),
    ]
