# Generated by Django 6.0 on 2026-04-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_calendarfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarfile',
            name='file',
            field=models.FileField(upload_to='calendars/'),
        ),
    ]
