# Generated by Django 6.0 on 2026-04-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_calendarfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarfile',
            name='file',
        ),
        migrations.AddField(
            model_name='calendarfile',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
