# Generated by Django 6.0 on 2026-04-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_calendarfile_file_calendarfile_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarfile',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
