# Generated by Django 6.0 on 2026-04-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(blank=True, choices=[('general', 'General Inquiry'), ('student', 'Student Services'), ('events', 'Events & Activities'), ('groups', 'Groups & Movements'), ('spiritual', 'Spiritual Guidance'), ('donations', 'Donations & Support'), ('partnerships', 'Partnerships')], max_length=50)),
                ('message', models.TextField()),
                ('newsletter', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
