# Generated by Django 6.0 on 2026-04-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('replied', 'Replied')], default='unread', max_length=10),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='category',
            field=models.CharField(choices=[('general', 'General Inquiry'), ('student', 'Student Services'), ('events', 'Events & Activities'), ('groups', 'Groups & Movements'), ('spiritual', 'Spiritual Guidance'), ('donations', 'Donations & Support'), ('partnerships', 'Partnerships')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
