# Generated by Django 6.0 on 2026-04-02 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('solemnity', 'Solemnity'), ('feast', 'Feast'), ('memorial', 'Memorial'), ('season', 'Season'), ('optional', 'Optional Memorial')], default='feast', max_length=20)),
                ('readings', models.JSONField(default=list)),
                ('verse', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendar Entry',
                'verbose_name_plural': 'Calendar Entries',
                'ordering': ['date'],
            },
        ),
    ]
