# Generated by Django 6.0 on 2026-04-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Our Father'", max_length=255, unique=True)),
                ('content', models.TextField(help_text='The actual text of the prayer')),
            ],
        ),
    ]
