# Generated by Django 6.0 on 2026-04-03 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0002_prayer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prayer',
            options={'ordering': ['name'], 'verbose_name': 'Prayer', 'verbose_name_plural': 'Prayers'},
        ),
    ]
