# Generated by Django 6.0 on 2026-04-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0003_alter_prayer_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarentry',
            name='verse',
        ),
        migrations.AddField(
            model_name='calendarentry',
            name='liturgical_color',
            field=models.CharField(blank=True, choices=[('white', 'White'), ('red', 'Red'), ('green', 'Green'), ('violet', 'Violet / Purple')], default=None, max_length=20, null=True),
        ),
    ]
