# Generated by Django 6.0 on 2026-02-19 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Prayer House', 'Prayer House'), ('Movement', 'Movement'), ('Year Group', 'Year Group'), ('Other', 'Other')], default='Prayer House', max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('members', models.CharField(blank=True, help_text='e.g. 80+', max_length=50)),
                ('meeting_time', models.CharField(blank=True, max_length=100)),
                ('meeting_location', models.CharField(blank=True, max_length=200)),
                ('communities', models.TextField(blank=True, help_text='Comma-separated community names')),
                ('chair', models.CharField(blank=True, max_length=150)),
                ('treasurer', models.CharField(blank=True, max_length=150)),
                ('secretary', models.CharField(blank=True, max_length=150)),
                ('about', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='group_gallery/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='groups.group')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
