# Generated by Django 6.0 on 2026-04-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name_plural': 'Groups'},
        ),
        migrations.AddField(
            model_name='group',
            name='is_alumni',
            field=models.BooleanField(default=False, help_text='Mark as Alumni Year Group'),
        ),
        migrations.AddField(
            model_name='group',
            name='meeting_day',
            field=models.CharField(blank=True, help_text='e.g. Saturdays, Thursdays', max_length=50),
        ),
    ]
