# Generated by Django 6.0 on 2026-04-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_options_group_is_alumni_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='group',
            name='communities',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_alumni',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='meeting_day',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
