# Generated by Django 6.0 on 2026-04-07 12:32

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_options_alter_group_communities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupimage',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='group_gallery/%Y/%m/%d/'),
        ),
    ]
