# Generated by Django 6.0 on 2026-04-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_groupimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='year',
            field=models.CharField(blank=True, choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year'), ('5', 'Fifth Year'), ('alumni', 'Alumni')], max_length=10),
        ),
    ]
