# Generated by Django 6.0 on 2026-04-02 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The main inspirational theme text')),
                ('image', models.ImageField(help_text='Theme banner image', upload_to='themes/')),
                ('year', models.CharField(help_text='e.g., 2024/2025 - Semester 2', max_length=50)),
                ('is_active', models.BooleanField(default=False, help_text='Only one theme should be active at a time')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Semester Theme',
                'verbose_name_plural': 'Semester Themes',
                'ordering': ['-is_active', '-date_created'],
            },
        ),
    ]
