# Generated by Django 6.0 on 2026-04-07 12:32

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='image',
            field=models.ImageField(help_text='Theme banner image', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='themes/'),
        ),
    ]
