# Generated by Django 6.0 on 2026-04-07 13:14

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_alter_theme_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='image',
            field=models.ImageField(help_text='Theme banner image', storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='themes/'),
        ),
    ]
