# Generated by Django 6.0 on 2026-04-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_alter_theme_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='image',
            field=models.ImageField(help_text='Theme banner image', upload_to='themes/'),
        ),
    ]
